// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MkunRZXMI2Js1G2BaY4Ygsj83CWw8nA',
    appId: '1:337599404062:web:273e5ac3bfc4689173760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    authDomain: 'emart-8d623.firebaseapp.com',
    storageBucket: 'emart-8d623.appspot.com',
    measurementId: 'G-EC015BWX2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_yw3e2EP24awtM9nYJ1Gq4guRxCr39k',
    appId: '1:337599404062:android:9ff34f5a89ef2e0973760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyExfnD3-lj27TQCK0xrxoD97ya_DyN0o',
    appId: '1:337599404062:ios:7f107d243dfc63ed73760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyExfnD3-lj27TQCK0xrxoD97ya_DyN0o',
    appId: '1:337599404062:ios:7f107d243dfc63ed73760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2MkunRZXMI2Js1G2BaY4Ygsj83CWw8nA',
    appId: '1:337599404062:web:b51fb1e82015815173760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    authDomain: 'emart-8d623.firebaseapp.com',
    storageBucket: 'emart-8d623.appspot.com',
    measurementId: 'G-21XQZYRS2C',
  );
}
